### ISSUE TITLE
[FEATURES] - Re-introduire des erreurs dans le sensor

### ISSUE THREAD

**Issue by vingerha** [MyElectricalData/myelectricaldata_import#401]
Les sensors ont l'option (attribute existante) pour enrégistrer des erreurs.
En ce moment ils sont hors service (toujours vide)
Use-case
Donner les utilisateurs accès vers des erreurs rapdidement, au lieu de ouvrir le container/add-on et chercher dans ces logs
Ensuite, je vais vois comment ça marche avec la carte Saniho

**Comment by m4dm4rtig4n** [comment]
Je viens d'ajouter une remonter d'erreur dans "errorLastCall" quand je détecte un soucis au niveau des consentements :
- "403 - Le point de livraison ne correspond au token fournis, pour le réinitialiser il vous suffit de refaire un consentement"

**Comment by vingerha** [comment]
Top, je ne peux pas tester avant mi-semaine...en route. Je vais voir aussi commenttu l'as fait pour que j; ajoute qq erreurs interne

**Comment by vingerha** [comment]
Est-ce qu'on peut avoir des erreurs plus déscriptive aussi?
Aujourd'hui j'ai ça (hier tout bon, rien changé)
```
2023-08-27 04:24:47.313 -     INFO : Récupération des données : 2020-08-29 => 2023-08-29
2023-08-27 04:24:54.623 -     INFO :  Chargement des données depuis MyElectricalData 2020-08-29 => 2023-08-29
2023-08-27 04:25:01.031 -    ERROR : Echec de la récupération des données
2023-08-27 04:25:01.032 -    ERROR : => Technical error. Please try later.
2023-08-27 04:25:01.032 -    ERROR : => 1929-05-29 -> 1932-05-29
```
Est-ce que c'est ton version de l erreur de Enedis? Ou c'est vraiment si intransparent ? Avec 'Technical error' je ne sais pas si chez moi (mqtt/bddd/etc.) ou toi ou Enedis

**Comment by m4dm4rtig4n** [comment]
Le soucis est que les erreurs peuvent provenir de tellement de source que c'est compliqué de les filtrer et savoir quoi envoyer.

**Comment by vingerha** [comment]
Closed as accepted
