### ISSUE TITLE
[BUG] - Souci de consentement

### ISSUE THREAD

**Issue by floow77** [MyElectricalData/myelectricaldata_import#411]
**Description du bug**
Depuis plusieurs jours, je ne reçois plus de nouvelles données, après analyses des logs, il semblerait que je dois renouveler mes consentements

2023-09-15 09:12:08.819 -     INFO : [22149782812540] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2023-09-15 09:12:08.820 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-15 09:12:08.839 -     INFO : Récupération des données : 2021-07-03 => 2023-09-17
2023-09-15 09:12:11.200 -     INFO : 127.0.0.1:54844 - "GET / HTTP/1.1" 200
2023-09-15 09:12:13.891 -     INFO :  Chargement des données depuis MyElectricalData 2021-07-03 => 2023-09-17
2023-09-15 09:12:14.813 -    ERROR : Echec de la récupération des données
**2023-09-15 09:12:14.814 -    ERROR : => Soucis au niveau des consentements, merci de les renouveller sur https://www.myelectricaldata.fr - Code d'erreur : 401 (cf. F.A.Q pour les codes d'erreurs)**
2023-09-15 09:12:14.814 -    ERROR : => 2021-07-03 -> 2023-09-17

Néanmoins, la page web de la passerelle m'indique que les consentements sont oK:

Expiration des consentements | 07/09/2026
Nombre d'appels journaliers | 12 / 500
Statut du compte |  coche verte

Quand j'essaie de renouveler les consentements, la page me renvoie une erreur 404.

**Type d'installation**
- Home Assistant 2023.9.2

**Version :0.9.1 **

**Comment by Shad107** [comment]
Bonjour,

A priori cela vient d'Enedis, message d'erreur :

![image](https://github.com/MyElectricalData/myelectricaldata/assets/11353965/574a3ddc-2f3f-4d7f-905f-ba5cc39b9ee7)

Cordialement,

**Comment by m4dm4rtig4n** [comment]
Oui les consentement sont actuelle HS chez Enedis.

La passerelle remonte juste que la synchro entre le client et la passerelle est OK.
Faudrait que je change le message.

**Comment by vgeannin** [comment]
J'ai exactement le même problème en ce moment pour un de mes abonnements, l'autre fonctionne bien
C'est vraiment bizarre

**Comment by Jeepmg** [comment]
Même souci.

Je ne vois nulle part apparaître la mise à jour 0.9.2.  Elle ne se fait pas. Il faut la forcer quelquepart ?

**Comment by floow77** [comment]
ça ne fonctionne toujours pas, avez-vous du nouveau ?

**Comment by m4dm4rtig4n** [comment]
Maintenance prolonger jusqu'au 3 octobres...

**Comment by plouf34** [comment]
nous sommes le 4 octobre 👎 (

**Comment by fmaitrot** [comment]
Bonjour, 
Est-ce que vous avez des nouvelles sur l'état de la plateforme de consentement ?
Merci pour le travail réalisé.

**Comment by aginies** [comment]
https://datahub-enedis.fr/services-api/etat-des-services/

**Comment by ftreil** [comment]
La demande de consentement enedis fonctionne. (Réaliser sur une autre plateforme jeudi dernier)

La demande de consentement de la plateforme myelectricaldata finit (depuis plus de 15 jours) de la même manière : 

l'url retourné par le site enedis est la suivante : https://gw.prd.api.enedis.fr/v1/oauth2/authorize?client_id=a33f059f-edd7-4650-a1d9-7b6768275677&response_type=code&redirect_uri=http://sandbox.myelectricaldata.fr/consent&user_type=B2B&state=null&person_id=PPPPPPPPPP&usage_points_id=XXXXXXXXXXXXX

Le message de cette url :
{
  "reasons" : [ ],
  "details" : {
    "msgId" : "Id-11de2c6518752fe45b675bc9"
  }
}

**Comment by m4dm4rtig4n** [comment]
> La demande de consentement enedis fonctionne. (Réaliser sur une autre plateforme jeudi dernier)
> 
> La demande de consentement de la plateforme myelectricaldata finit (depuis plus de 15 jours) de la même manière :
> 
> l'url retourné par le site enedis est la suivante : https://gw.prd.api.enedis.fr/v1/oauth2/authorize?client_id=a33f059f-edd7-4650-a1d9-7b6768275677&response_type=code&redirect_uri=http://sandbox.myelectricaldata.fr/consent&user_type=B2B&state=null&person_id=PPPPPPPPPP&usage_points_id=XXXXXXXXXXXXX
> 
> Le message de cette url : { "reasons" : [ ], "details" : { "msgId" : "Id-11de2c6518752fe45b675bc9" } }

Ca fonctionne quand la configuration chez Enedis est correcte...
Sauf que le portail d'Enedis était HS pendant 15j (après 15j de maintenance), et j'ai fait une demande de changement de configuration il y a 1 semaines pour remettre en route myelectricaldata, sauf qu'Enedis à ce jour n'a tjr pas traiter la demande...

**Comment by cvalentin-dkt** [comment]
Quand tu vois le message suivant sur leur portail ta comprit qu'il faut pas trop en demander :

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/81801129/d39a6b67-d47a-495f-923e-87840186a58f)

**Comment by grrosminet** [comment]
Si je comprend bien l'état des API, leur V5 marche parfaitement puisque personne ne peut se connecter ?

**Comment by cvalentin-dkt** [comment]
Petit récap :
En gros leurs API V5 est en ligne depuis des mois et la migration final c'est effectuer le 13 septembre.

Dans mon cas, je ne voulais pas migrer avant car avec le passage à la V5, Enedis à retirer une fonctionnalité important pour le fonctionnement de ma passerelle (surtout pour les utilisateurs avec plusieurs compteur Linky sur leurs compte).
Et ils m'avaient dit qu'ils allez réintégrer cette fonctionnalité lors de la migration du 13 septembre.
Je le donne dans le mille, que le peu de test que j'ai réussi à faire entre 2 sur la V5 depuis la mise en production n'intègre pas cette fonctionnalité...
=> Bref j'ai une solution de contournement en attendant qui demande au utilisateurs finaux de faire une demande de consentement par points de livraison.

Mais le soucis principal est que la mise en production du 13 septembre à durée 15j, puis le portail Enedis HS pendant 15j (nécessaire pour que je finalise la migration vers la v5), et la depuis le 10 j'ai une demande de changement de configuration sur le portail en attente...

En gros, "normalement" dés qu'Enedis aura traité ma demande le service sera de nouveau opérationnel.

**Comment by Jeepmg** [comment]
@cvalentin-dkt Dataconnect API bac a sable est opérationnel .

Reste juste API production Authorize en maintenence.. 

Ca devrait faire avancer le retour à la normale.

**Comment by Jeepmg** [comment]
@m4dm4rtig4n Il n'y a toujours pas moyen de migrer les API ou c'est trop tard ???

Nous attaquons le deuxième mois d'attente. Il est vrai que baser sa stratégie de mise à jour sur une éventuelle amélioration Enedis qui en plus ne concerne d'une frange marginale des utilisateurs n'est pas des plus sécure.

**Comment by m4dm4rtig4n** [comment]
Depuis hier soir et suite à une parade qu'un utilisateur m'a transmise, il est de nouveau possible de faire des consentements 💯 
Tt est expliquer sur la homepage https://myelectricaldata.fr : 

1 - Faire le consentement normalement.

2 - Au moment de la redirection vers l'URL "https://gw.prd.api.enedis.fr/v1/oauth2/..." qui vous retourne un fichier JSON, merci de remplacer "gw.prd.api.enedis.fr" par "myelectricaldata.fr" dans l'URL.

Exemple du fichier JSON:
```
{
    "reasons": [],
    "details": {
    "msgId": "Id-XXXXXXXXXXXXXXXX"
    }
}
```

3 - Un "endpoint" temporaire va gérer la redirection vers la bonne adresse sur MyElectricalData.

**Comment by Jeepmg** [comment]
Ca fonctionne, merci

**Comment by vgeannin** [comment]
Merci pour l'info, cela fonctionne maintenant

**Comment by Jeepmg** [comment]
Espoirs de courte durée, pas de remontées d'info de la journée d'hier.

**Comment by m4dm4rtig4n** [comment]
Ouai je viens de voir le soucis, je pense que c'est chez moi...
Avec la V5 il ont changer un retour en cas d'expiration du token temporaire et au lieu de m'envoyer une 403, il m'envoie un json vide...

**Comment by Jeepmg** [comment]
et ??? c'est réparable ou on est reparti pour un mois ?

**Comment by m4dm4rtig4n** [comment]
Non l'avantage c'est que j'ai la main sur cette partie :D
Faut juste que je trouve un peu de temps et que je suis en congés cette semaine avc bcp de travaux à la maison...
Bref je vous tiens au jus.

**Comment by Dautrip** [comment]
Il y a du mieux c’est cool, j’ai l’impression que le token récupéré n’est valable que quelques heures, c’est normal ?

**Comment by vgeannin** [comment]
> Non l'avantage c'est que j'ai la main sur cette partie :D Faut juste que je trouve un peu de temps et que je suis en congés cette semaine avc bcp de travaux à la maison... Bref je vous tiens au jus.

Hello,

tu as réussi a résoudre le PB ?

Merci

**Comment by DrumSlayers** [comment]
À ce jour, j'ai l'impression qu'ENEDIS est allé encore plus loin dans le cassage de leur API.
Sur la page de consentement (https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize?client_id=xxxx) : Page blanche
Une inspection dans la console nous indique une erreur CORS
`Access to XMLHttpRequest at 'https://kiamo-chatlive-noe.enedis.fr/js/kiamo-chat-6330cc2787268d699a20940cd99d2787.min.js' from origin 'https://mon-compte-particulier.enedis.fr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.)`
Un bypass des protections CORS (Chrome) n'avance rien non plus : On obtient juste une erreur 500
```
polyfills.js:1 
GET https://alex.microapplications.enedis.fr/mes-consentements/api/private/v1/personnes/PIB730PTR/tiers/a33f059f-edd7-4650-a1d9-7b6768275677 500 (Internal Server Error))
```

Quelqu'un à une solution pour contourner ça ? Car pour le moment, impossible de faire la première étape, et donc la solution de bypass indiquée sur la homepage de myelectricaldata ne sert plus à rien ^^
Merci

**Comment by DrumSlayers** [comment]
> À ce jour, j'ai l'impression qu'ENEDIS est allé encore plus loin dans le cassage de leur API. Sur la page de consentement [...]

Ok, petit update du cassage de ENEDIS par ENEDIS
La page blanche n'est plus, alors que ça faisait quelques jours que c'était HS (Faut-il croire qu'un dev de chez eux scrute ici ?).
Cependant, le consentement est toujours impossible 🥳: Mes deux compteurs linky sont grisés "compteur incompatible", le nom de l'application et la liste des données demandées ne s'affichent même pas. 
bref, c'est toujours cassé chez eux.

![Capture d'écran 2023-11-14 114520](https://github.com/MyElectricalData/myelectricaldata_import/assets/4050278/ae4b8d28-e002-4783-a6e9-c8521ad18a67)

![Capture d'écran 2023-11-14 114630](https://github.com/MyElectricalData/myelectricaldata_import/assets/4050278/97c82c02-77d0-4365-a8e1-e4425751d7ce)

**Comment by Bambouzle** [comment]
Le consentement a fonctionné aujourd'hui pour moi. Par contre je ne les (oui je l'ai validé plusieurs fois 😅) vois pas depuis l'onglet "gérer l'accès à mes données > partage des données". Mais j'ai une remontée des données dans Home Assistant 👌

**Comment by bcrosnier** [comment]
J'ai aussi l'erreur "Compteur incompatible".

Le client OAuth2 `a33f059f-edd7-4650-a1d9-7b6768275677` (MyElectricalData) ne semble pas ou plus exister sur leur backend, et ne renvoie aucun consentement à approuver via leur API `/api/private/v1/personnes/{personId}/tiers/{clientId}`.

C'est vérifiable en mettant n'importe quoi comme clientId - vous pouvez aller sur https://mon-compte-particulier.enedis.fr/dataconnect/v1/oauth2/authorize?client_id=AAAAAAAAAA&duration=P36M&response_type=code et vous verrez la même page s'afficher, avec le clientId "AAAAAAAAAA" (n'existant pas) qui ne demande aucun consentement et l'erreur "Compteur incompatible".

**Comment by m4dm4rtig4n** [comment]
Tt est de nouveau opérationnel à 100%.

**Comment by nelscougar** [comment]
J'ai moi aussi "Compteur incompatible". Pénible ENEDIS...... impossible de récupérer mon TOKEN.

**Comment by thomas-maurice** [comment]
J'ai un souci aussi pour la demande de consentement, je vois cettte erreur

![Screenshot from 2024-06-14 16-06-19](https://github.com/MyElectricalData/myelectricaldata_import/assets/3941401/77818794-b6a6-4bdd-9b62-c611ae38be0d)

En regardant ce qu'il se passe j'ai l'impression que c'est un souci de CORS mais je ne sais pas comment le résoudre, quelqu'un a une idée ?

**Comment by jmcruvellier** [comment]
Bonjour, la demande de consentement ne semble plus fonctionner. Comme pour d'autres je me retrouve avec "compteur incompatible". Quelqu'un a-t-il trouvé une solution de contournement?

**Comment by olivierdomy** [comment]
Bonjour. J'ai le même problème. Plus de données remontées et consentement invalide. Sur le site Enedis, j'ai la mention "Compteur incompatible". Y a t'il une solution de contournement existante svp?

**Comment by DrumSlayers** [comment]
> Bonjour. J'ai le même problème. Plus de données remontées et consentement invalide. Sur le site Enedis, j'ai la mention "Compteur incompatible". Y a t'il une solution de contournement existante svp?

Oui, c'est à nouveau cassé de mon côté aussi depuis fin aout.
Pas de soluce à priori pour le moment

**Comment by AldoLodos** [comment]
Idem pour moi. Plus de données remontées et consentement invalide. et   "Compteur incompatible" sur le site Enedis
Pas de nouvelles ?

**Comment by m4dm4rtig4n** [comment]
Malheureusement sur le message d'erreur "Compteur incompatible", le soucis est chez Enedis est je l'espère en cours de résolution chez eux...
Je les ai encore relancer il y a 2 semaine, je vais relancer une 3eme mail de relance.

**Comment by jmcruvellier** [comment]
Pour info, ça remarche côté Enedis depuis aujourd'hui:
![image](https://github.com/user-attachments/assets/d04527e7-de7f-47b1-b34d-f14a4fbdabcf)

**Comment by DrumSlayers** [comment]
> Pour info, ça remarche côté Enedis depuis aujourd'hui: ![image](https://private-user-images.githubusercontent.com/14132271/387713505-d04527e7-de7f-47b1-b34d-f14a4fbdabcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTgxMTYsIm5iZiI6MTczMjExNzgxNiwicGF0aCI6Ii8xNDEzMjI3MS8zODc3MTM1MDUtZDA0NTI3ZTctZGU3Zi00N2IxLWIzNGQtZjE0YTRmYmRhYmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE1NTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwN2RmMGNmZTA3NjBhMGExZjU1MTliMjc0MTQyNDM3Nzk0YTUyYWUzNDM4OGYzYTYxYWQ2M2JhZThmMzM0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3n-hfe9o3FKkRSviBrUw0ekj98AoOU25yC9Qj2ukAdI)

Je confirme, consentement OK mais aucune données remontées chez ENEDIS depuis 20/10/2024 de toute façon chez moi. Je sais pas si c'est général ou si c'est juste souvent pété.
À ce stade, je vais juste investir dans un module TIC 🥲
![image](https://github.com/user-attachments/assets/2cf2bfc1-719f-4ea2-86ae-6f87ed31b69c)
