### ISSUE TITLE
[HELP] - plus de collecte de données depuis le 19/09 sur HAOS via Mqtt est ce lié a la plateforme Enedis car idem sur la page web myelectricla data les consentements sont actifs.merci

### ISSUE THREAD

**Issue by Greg030779** [MyElectricalData/myelectricaldata_import#422]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description de la fonctionnalité**

**Type d'installation**
HAssio

**Version : 2023..9.3*
Myelectricaldata : 0.9.2

**Comment by jpsuter** [comment]
same for me, no data.
In the log : 
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 120, in run
    for interval_reading in meter_reading["interval_reading"]:
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-10-04 17:30:29.345 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 283, in get_consumption_detail
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 272, in run
    Detail(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_detail.py", line 200, in get
    if "exit" in response:

**Comment by m4dm4rtig4n** [comment]
Oui le service est HS pour l'instant, Enedis est en maintenance depuis 3 semaines....

**Comment by Greg030779** [comment]
Ok merci,
Comme c’était inique jusqu’au 29 de mémoire et que j’ai les données sur le site d’énedis.

Gregory MARTIN


Le 4 oct. 2023 à 17:58, m4dm4rtig4n ***@***.***> a écrit :

﻿

Closed #422<https://github.com/MyElectricalData/myelectricaldata_import/issues/422> as completed.

**Comment by m4dm4rtig4n** [comment]
Oui initialiement...
C'est afficher aux 3 octobre depuis 1 semaine et après 3 mails au support rien ne bouge chez eux...
