### ISSUE TITLE
[FEATURES] - Ajout de la possibilité de se connecter en HTTPS à influxdb

### ISSUE THREAD

**Issue by vgeannin** [MyElectricalData/myelectricaldata_import#424]
Est-ce qu'il serait possible d'ajouter la possibilité de se connecter en HTTPS à influxdb
donc de passer (dans le fichier "models/influxdb.py") de  
                url=f"http://{self.hostname}:{self.port}" 
            à  url=f"https://{self.hostname}:{self.port}" 
en fonction d'une variable dans le fichier de config

Merci

**Comment by m4dm4rtig4n** [comment]
Hello,

Je viens d'ajouter la fonctionnalité qui arrivera avec la prochaine update :)
