### ISSUE TITLE
Feature - créer un cache.db a partir d'un fichier

### ISSUE THREAD

**Issue by PHB-fra** [MyElectricalData/myelectricaldata_import#430]
A partir d'un téléchargement des données sur le site enedis pouvoir générer un fichier caché.db

Par avance merci

**Comment by m4dm4rtig4n** [comment]
Qu'elle est l'utilité dans le sens où le client récupére exactement les même données ?

**Comment by PHB-fra** [comment]
En fait aucun, c'etait suite a un probleme de changement de contrat mon cache.db a "perdu" 2 ans.
En réduisant la date d'interrogation et avec un backup j'ai pu retrouver l'ensemble de mon PDL
