### ISSUE TITLE
[DOCUMENTATION] - Fix typo

### ISSUE THREAD

**Issue by FabienPennequin** [MyElectricalData/myelectricaldata_import#432]
**Description du bug**
Tout d'abord merci pour ce projet bien utile et qui me permet d'en finir avec mes imports/exports Enedis à la main :)

J'ai suivi la documentation (wiki) pour l'installation du projet et j'ai croisé quelques petites typos et URL hs, notamment celle du dashboard grafana.

Si cela peut aider de futurs utilisateurs, je vous propose un fichier patch (comme Github ne permet les PR sur le wiki) : [fix_typo.txt](https://github.com/MyElectricalData/myelectricaldata_import/files/13297206/fix_typo.txt)
 (fichier en .txt parce que Github n'accepte pas le .patch non plus)

**Type d'installation**

- [ x] Docker

**Version : 0.9.2**

**Comment by m4dm4rtig4n** [comment]
Thx j'essaie de faire ca prochainement ;)
