### ISSUE TITLE
[FEATURES] - Ajout des entités importés par WS

### ISSUE THREAD

**Issue by vingerha** [MyElectricalData/myelectricaldata_import#434]
Pour améliorer l'usage des statistiques longe termes, je propose d'ajouter des entitiés 'virtuels' avec les  même noms de ceux qui sont importer par le WS
Plus:
- facile a ajouter dans energy dash
- ouvrir l'utilisation dans p.e.. Apexcharts

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/44190435/9959db79-21bc-45f7-8904-0c9fcc14c228)

Dand statistics ça marche
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/44190435/95c2e6d1-1ed6-4dfe-aedf-5753b8974e00)

**Comment by m4dm4rtig4n** [comment]
Si je crée un sensor avec 2 ans d'historique et des data par tranche de 30min, autant dire que le sensor va mettre des plombes à charger et HA remontera des warning à son sujet.
Je ne pense pas que ce soit la bonne méthode.

**Comment by vingerha** [comment]
C'est pas 'méthode' ... sans sensor de base ça ne marche pas bien. J'ai pensé d'avoir juste un sensor 'dummy' qui est liée (même om/id) avec long-term stats, pas nécessaire d'avoir des historiques

**Comment by m4dm4rtig4n** [comment]
Mais actuellement il est déjà possible de faire de l'apex chart avec les sensor envoyer sur HA, je comprend pas trop l'intéret d'en rajouter encore avec une information similaire.
Exemple : 
https://forum.hacf.fr/t/les-cartes-et-myelectricaldata/19996?page=5

**Comment by m4dm4rtig4n** [comment]
Hello @vingerha , mon dernier post correspond à ton besoin en fin de compte ou non ?

**Comment by vingerha** [comment]
Non, ça ne va pas...montre le code / yaml stp

**Comment by m4dm4rtig4n** [comment]
En fait le soucis c'est que je ne peut pas crée de sensor avec une donnée dans le passé (limitation de HA).

Pour créer ce type de sensor, il faudrait que j'envoie la donnée tt les 30min le jour J mais comme je n'ai pas de donnée en temps réel c'est compliqué...

Après je sais qu'il est possible de le faire via apexchart en ajoutant un décalage, mais la donnée serait tjr en J-1 mais c'est merdique.

**Comment by vingerha** [comment]
J'ai pas la solution directement mais il n'y a pas besoin d'avoir des valeurs pour ce sensor.
En fait avec l'import des statistiques sans sensor de base MED a crée une incohérence car normalement il faut avoir un sensor pour crée des statistiques. Avec l'incoh;erence qq fonctionalités ne marchent pas. Je me rapelle d'avoir promis de tester qqc mais j'ai oublié de le faire...je vais re-essaier dans les semaines qui viennent. Si pas de solution proposé vers fin Fév. tu peux le fermer, ok?

**Comment by m4dm4rtig4n** [comment]
J'ai créer des sensor :
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/7872518/731d77e7-f3f2-4d1e-8c09-1f51cb0a27ae)

**Comment by vingerha** [comment]
OK, je pensais de me focusser la semaine prochaine...t'tes trops vite :) ... c'est ou dans ton code?

**Comment by m4dm4rtig4n** [comment]
https://github.com/MyElectricalData/myelectricaldata_import/blob/5ed9171ef952737e46a6a7f8a0c2e4c9aac764cc/src/models/export_home_assistant_ws.py#L345

**Comment by m4dm4rtig4n** [comment]
@vingerha c'est en ligne avec la 0.13.0-RC.1

**Comment by vingerha** [comment]
Merci, je suis dans la montagne pour le ski (neige partout) mais je vais voir/tester dans la semaine

**Comment by vingerha** [comment]
Salut, je n'ai pas oublié ce sujet. J'ai apris comment utiliser l'api en l'ajoutant dans meters2ha pour mon gazpar. Le comportement de HA est curieux/instable car même visible dans la bdd je ne pourrais pas les ajouter dans le dash élec, refresh écran à changé la sélection aussi et une fois mes données ont disparu ...  J'ai cherché le support avec les devs de HA (discord) mais pour le moment pas grand chose de retour.
Ce que je voullait éviter avec l'entité de base est ça
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/44190435/42fdfb17-cd9f-4e0b-a438-9dcdc97441d7)

**Comment by vingerha** [comment]
J'ai finalement pu tester mais... c'est pas bon. Le nom du sensor doit être identique au nom du sensor dans les statistiques. Je viens de créer une propre situation dans 'mon' gazpar_2_mqtt. 
Tes statistiques ont un nom assez différent que celles du standard p.e. myelectricalData:25960347298299_blue_consumption au lieu de sensor.linky. Donc il faut changer le nom des statistiques aussi. .. sais pas si t'es intéressé aussi car je ne voix pas beaucoup d'intérêt das autres ...peut-être ils n'utilisent pas Apex ?

**Comment by vingerha** [comment]
Je viens de créer ça

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/44190435/419242be-9ad2-4fab-933f-aae5b4d26655)

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/44190435/56e2ce54-ed87-42ad-b6d1-2764d44757bd)

Et avec ça je peux créer l'apex aussi

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/44190435/0843c49e-fb5e-4855-ba19-95ee100bb2b9)

**Comment by vingerha** [comment]
Donc, j'ai finalement compris que c'est impossible suivant l'architecture de HA. 
Pour les stats ext. il faut l'avoir ne statistic_id formatés avec le ': '  ... je ne sais pas qui a inventé çe truc curieux / intattendu ... 
J'abandonne aussi mes essais pour gazpar_2_mqtt et j'attend une réponse favorable sur un feature request chez apexcharts (pas trops de confiance)
