### ISSUE TITLE
[FEATURES] - Ajoute Tempo-days dans le sensor pour être utilisé dans la carte

### ISSUE THREAD

**Issue by vingerha** [MyElectricalData/myelectricaldata_import#436]
Puisque on oublie quelle 'tempo' était appliqué (p.e.) avant-hier, je propose d'ajouter les couleurs puisque les gens peuvent visualiser aussi une expliquation autour la différence de prix.
Format proposé, aligné avec les données déjà visibles
```
dailyweek_tempo:
  - "white"
  - "blue"
  - "blue"
  - "blue"
  - "blue"
  - "blue"
  - "red""

**Comment by vingerha** [comment]
Si je trouve du temps je te fait un PR et aussi pour la carte

**Comment by m4dm4rtig4n** [comment]
En ce moment j'ai pas mal de taff en même temps, ca devrait allez mieux
prochainement et retrouver un peu de temps pour MED :D

**Comment by vingerha** [comment]
t'as déjà tous dans database et stat donc juste export_homeassistant a faire, non?
Au niveau des hp/ch ... tu sais qu'il existe une situation quand tempo-hp et tempo-hc sont différent le même jour?

**Comment by m4dm4rtig4n** [comment]
C'est lié à ta PR ?
https://github.com/MyElectricalData/myelectricaldata_import/pull/439

**Comment by vingerha** [comment]
Oui, fermé...merci
