### ISSUE TITLE
[BUG] - Plus d'import depuis le 27/11 00:30

### ISSUE THREAD

**Issue by alpha13fr** [MyElectricalData/myelectricaldata_import#437]
**Plus d'import depuis le 27/11**
Bonjour,
Plus d'import depuis le 27/11 00:30
Tout était ok auparavant , a part un "trou" chez enedis qui semble ne pas avoir mes données avant 05/2023
mais ok
Merci

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
```
</details>

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : X.X.X**

**Comment by yoyomax80400** [comment]
Même problème pour ma part depuis 28/11 à 00h00
Plus aucune data ensuite

**Comment by m4dm4rtig4n** [comment]
Avez vous vérifier sur le site d'Enedis que vous avez bien de la donnée qui remonte sur ces dates ?

Pensez également à vérifier que le relevé Horaire & co sont tjr actif.
=> https://www.myelectricaldata.fr/faq

Sinon envoyer moi vos logs :)

**Comment by yoyomax80400** [comment]
> Avez vous vérifier sur le site d'Enedis que vous avez bien de la donnée qui remonte sur ces dates ?
> 
> Pensez également à vérifier que le relevé Horaire & co sont tjr actif. => https://www.myelectricaldata.fr/faq
> 
> Sinon envoyer moi vos logs :)

Je confirme que tout est ok sur Enedis ... les datas comme le relevé actif

**Comment by Pepeanuts** [comment]
Même problème.

Quand je test avec les commandes : 

```
curl -s -X GET "https://www.myelectricaldata.fr/consumption_load_curve/xxxxxxxxx/start/2023-11-24/end/2023-11-30" -H "Authorization: yyyyyyyyyyyyyy"  | jq
{
  "detail": "Technical error. Please try later."
}
root@:~# curl -s -X GET "https://www.myelectricaldata.fr/consumption_load_curve/xxxxxxxxx/start/2023-10-27/end/2023-11-02" -H "Authorization: yyyyyyyyyyyyyy"  | jq
{
  "detail": "Technical error. Please try later."
}
root@:~# curl -s -X GET "https://www.myelectricaldata.fr/contracts/xxxxxxxxx/" -H "Authorization: yyyyyyyyyyyyyy"  | jq
{
  "detail": "No consent can be found for this customer and this usage point."
}
root@:~# curl -s -X GET "https://www.myelectricaldata.fr/valid_access/xxxxxxxxx/" -H "Authorization: yyyyyyyyyyyyyy"  | jq
{
  "valid": true,
  "information": "",
  "consent_expiration_date": "2026-10-25T14:54:24",
  "call_number": 27,
  "quota_reached": false,
  "quota_limit": 50,
  "quota_reset_at": "2023-12-01T23:59:59.999999",
  "last_call": "2023-10-25T14:54:24.508062",
  "ban": false
}
```

Visiblement un mélange de consentement autorisé et refusé.
Nouvelle demande de consentement à faire ?

**Comment by Pepeanuts** [comment]
Après renouvellement du consentement c'est ok.

**Comment by alpha13fr** [comment]
renouvellement clef et tout est ok
Je cloture

**Comment by alpha13fr** [comment]
renouvellement clef et ca redemarre
