### ISSUE TITLE
Configuration PostgreSQL

### ISSUE THREAD

**Issue by ffries** [MyElectricalData/myelectricaldata_import#440]
Bonjour à tous,

Tout d'abord un grand bravo pour le développement de ce service. A mon domicile, je n'ai pas accès au compteur Linky qui se trouve dans une salle commune de l'immeuble.

J'utilise Home Assistant en docker natif et j'ai l'habitude d'utiliser PostgreSQL. Le projet indique supporter PostgreSQL. Est-ce la cas ? Quelle est la configuration ?

Si j'utilise Home Assistant avec une base de données PostgreSQL, quel est l'intérêt de stocker les données dans une base externe à Home Assistant ?

Cordialement,
FF

**Comment by m4dm4rtig4n** [comment]
Hello,

Il suffit de définir la ligne suivante dans le config.yaml :
https://github.com/MyElectricalData/myelectricaldata_import/blob/35ded9a7aece1958dd8a3569177ea94d93ac6cd3/config.exemple.yaml#L8

**Comment by ffries** [comment]
Merci, cela me simplifie beaucoup les choses.

**Comment by ffries** [comment]
Merci beaucoup, cela me simplifie beaucoup les choses.

**Comment by ffries** [comment]
Bon, je rouvre car je ne suis pas certain d'avoir compris.

Toutes les données seront importées dans un cache local (SQLite) ou externe (PostgreSQL) qui pourrais ensuite être exporté vers :

```
    MQTT
    Home Assistant (Via l'auto-discovery MQTT)
    InfluxDB
    PostgresSQL

```
Home assistant est déjà sous PostgreSQL. Il me suffit d'utiliser le cache local et d'exporter vers mqtt ? Pourquoi exporter vers InfluxDB ? Merci
