### ISSUE TITLE
[BUG] - écarts de consommation pour l'année en cours

### ISSUE THREAD

**Issue by grrosminet** [MyElectricalData/myelectricaldata_import#441]
**Description du bug**
Dans le récapitulatif de consommation annuelle : l'écart de consommation ne tient pas compte du jour et fait mirroiter une diminution de la consommation tout au long du mois pour ne pas avoir l'occasion de voir la réalité puisque la conso du dernier jour n'est connue que le lendemain.

==> il faudrait donner l'écart de consommation à la même date

**Version : 0.9.2**

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/3082795/2c351d2f-4000-4e2c-a535-f7b5578b7f67)

**Comment by m4dm4rtig4n** [comment]
Ce sera fix avec la 0.9.3.

Exemple :
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/7872518/85b6366b-d16a-4bd9-845f-4ca5e988ae31)

**Comment by grrosminet** [comment]
Bonjour
j'ai installé la 0.9.3 hier soir , mais rien n'a changé 😭

**Comment by m4dm4rtig4n** [comment]
Tu est sûr d'avoir bien basculer sur la 0.9.3 ?
Bizarre chez moi car j'ai bien la modification entre les 2 :/

**Comment by grrosminet** [comment]
C'est ce que m'affiche la page d'accueil de MyElectricalData dans Home Assistant .... comment puis-je vérifier autrement ?

**Comment by grrosminet** [comment]
Je viens de supprimer le module et de le réinstaller : toujours pareil

**Comment by grrosminet** [comment]
J'ai basculé sur le module de DEV (0.9.4b3) et ca fonctionne bien
