### ISSUE TITLE
[BUG] - illisible sur smartphone

### ISSUE THREAD

**Issue by grrosminet** [MyElectricalData/myelectricaldata_import#442]
**Description du bug**
Sur un téléphone (dans l'appli home assistant ou sur le site web home assistant), certaines données sont illisible car trop petites

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/3082795/5e022063-4f53-4469-b226-7e896c87ff53)

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : 0.9.2**

**Comment by m4dm4rtig4n** [comment]
Je n'ai effectivement pas du tt prévu l'affichage sur mobile :D

**Comment by m4dm4rtig4n** [comment]
Je viens de check chez moi et en fait c'est surtout le mode iframe depuis HAOs qui deforme énormément l'affichage :/
En pleine page "classic", même sur mobile c'est largement visible.

Il faudrait que je bascule sur une interface 100% responsive mais clairement je ne sais pas si la fonctionnalité verra le jour un jour.
