### ISSUE TITLE
[BUG] - Pb de certificat SSL avec myelectricaldata.fr

### ISSUE THREAD

**Issue by DamsPer** [MyElectricalData/myelectricaldata_import#444]
**Description du bug**
Depuis ce matin la récupération des infos ne fonctionne plus car le certificat SSL de myelectricaldata.fr n'est pas valide.

<details>
2023-12-08 10:13:10.595 -    ERROR : HTTPSConnectionPool(host='myelectricaldata.fr', port=443): Max retries exceeded with url: /ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
<img width="450" alt="image" src="https://github.com/MyElectricalData/myelectricaldata_import/assets/37600937/d7447fb5-7b2e-4b3d-971a-03e9fac3f721">

</details>

**Type d'installation**

- [x] HassIO

**Version : 0.9.2-6**

**Comment by ZaGaPonG** [comment]
Hello,

Same problem here: `HTTPSConnectionPool(host='myelectricaldata.fr', port=443): Max retries exceeded with url: /daily_consumption_max_power/XXXX/start/2020-12-09/end/2020-12-10/cache/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))`

Thanks in advance

**Comment by Shadow38ha** [comment]
Hi,

Same for me too : ERROR : HTTPSConnectionPool(host='myelectricaldata.fr', port=443): Max retries exceeded with url: /ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))

thanks

**Comment by alpha13fr** [comment]
certificat non renouvelé pour myelectricaldata.fr ?

**Comment by m4dm4rtig4n** [comment]
J'ai migrer le service sur un nouveau serveur et j'ai un petit soucis sur la partie TLS/SSL...

Je vous tiens au courant, en attendant vous pouvez désactiver le check TLS/SSL : 
https://github.com/MyElectricalData/myelectricaldata_import/blob/35ded9a7aece1958dd8a3569177ea94d93ac6cd3/config.exemple.yaml#L20C1-L21C16
=> Suffit de le mettre à "false"

**Comment by Doubledom45** [comment]
Ok Pour moi !merci @m4dm4rtig4n

**Comment by ZaGaPonG** [comment]
Je confirmes, merci

**Comment by DamsPer** [comment]
Je confirme aussi. Merci beaucoup, très réactif 👍
