### ISSUE TITLE
[FEATURES] - importer dans HA à partid d'un date configuré

### ISSUE THREAD

**Issue by vingerha** [MyElectricalData/myelectricaldata_import#445]
L'import par ws prends toutes les données détails. Souvent les gens, comme moi, ont déjà des données dans le dash Energie, basé su p.e. Linky et, comme moi, sur un autre contrat/prix. 
Je propose que l'import se base sur une date dans config.yaml. J'ai vu que ça sera par trop difficile..
```
detail = DB.get_detail_all(self.usage_point_id, order_dir="desc")
```
peut avoir aussi 'begin'

**Comment by egavard** [comment]
Hello,

Si j'ai bien compris, je crois que tu peux utiliser `consumption_detail_max_date` et `consumption_max_date` dans la config pour limiter la date à laquelle le soft remonte pour récupérer les data de conso

**Comment by m4dm4rtig4n** [comment]
Effectivement, mais je pense qu'il veut surtout limite l'import dans l'onglet Energy de HA mais avoir quand même la totalité des données sur les sensor créer par MED.
Je peut voir pour essayer d'ajouter la fonctionnalité.

**Comment by m4dm4rtig4n** [comment]
La fonctionnalité arrive à partir de la 0.10.1-rc.3 avec le new params max_date dans la configuration du hom_assistant_ws.
