### ISSUE TITLE
Can't install ghcr.io/alexbelgium/myelectricaldata-amd64:0.9.3: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.9.3&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")[BUG] - 

### ISSUE THREAD

**Issue by Jeepmg** [MyElectricalData/myelectricaldata_import#447]
**Description du bug**

@alexbelgium Can't install ghcr.io/alexbelgium/myelectricaldata-amd64:0.9.3: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.9.3&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

<details>

Meme message d'erreur que lors de la dernière mise à jour le samedi

**Type d'installation**

- [ ] Docker
- [ X] HassIO

**Version : La dernière si je pouvais !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by cvalentin-dkt** [comment]
@Jeepmg ta résolu ton soucis ?
Poste plutôt directement sur le GH d'alexbelgium la prochaine fois :)
=> https://github.com/alexbelgium/hassio-addons/issues

**Comment by Jeepmg** [comment]
BonjourOui ça a fini par fonctionner. Merci. Cordialement. Envoyé de mon iPhoneLe 18 déc. 2023 à 09:55, Clément VALENTIN ***@***.***> a écrit :﻿
@Jeepmg ta résolu ton soucis ?
Poste plutôt directement sur le GH d'alexbelgium la prochaine fois :)
=> https://github.com/alexbelgium/hassio-addons/issues
