### ISSUE TITLE
[BUG] - DataTables warning: table=dataTableConsommationDetail - Ajax Error

### ISSUE THREAD

**Issue by BetyOops** [MyElectricalData/myelectricaldata_import#457]
Bonjour à tous :)

Bonne année et meilleurs voeux !

**Description du bug**
Pop-up d'erreur à l'ouverture après sélection de mon pdl dans la liste déroulante.
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/57355664/177b374b-e942-4901-8ba9-a7d9a5fa17a5)

C'est cette requete ajax qui ne passe pas dans le debogueur FF: 

``` https://mondomaine/datatable/04330969527103/consumption_detail?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1704556400971``` 

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/57355664/acc7b54f-56c7-48c7-ac18-a2c0d4554293)

**Type d'installation**

- [x] Docker
- [x] Nginx proxy manager
- [x] Authelia

**Version : 0.9.4b3**

**Comment by BetyOops** [comment]
Je m’autoreply pour orienter: le probleme proviens lorsque on passe en https pour interroger myelectricaldata. Aucun soucis en http.

**Comment by m4dm4rtig4n** [comment]
Du coup tt est bon de ton côté ?

**Comment by BetyOops** [comment]
Du coup oui :) Tout est bon! 👍
