### ISSUE TITLE
[FEATURES] - Bug ou new feature ? :) Suivi HP / HC

### ISSUE THREAD

**Issue by Dites33** [MyElectricalData/myelectricaldata_import#459]
Bonjour

Je suis actuellement sur la derniere version prod, tout fonctionne bien, j'ai mes relevés de consommation qui tombent dans home Assistant.

Je ne suis pas en HP / HC.
Dans mon tableau de PDL, je vois des horaires HP / HC

`Lundi | Mardi | Mercredi | Jeudi | Vendredi | Samedi | Dimanche
21H06-5H06 | 21H06-5H00 | 21H06-5H06 | 21H06-5H06 | 21H06-5H06 | 21H06-5H06 | 21H06-5H06`

Jusque là tout va bien

Par contre j'ai mes données de consommations et là j'ai un problème car pour myelectricaldata, j'ai 99,8 % en HP et 100 % pour 2024 MAIS niveau prix ... j'ai une différence

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/14044648/4b5e33b5-4040-4b20-be65-9d96d655b340)

Du coup est ce normal ? J'aimerai bien, si c'est normal, que myelectrical data me montre mon % en HP / HC comme pour le prix :)

Du coup ... bug ou demande de feature ? :)

Merci :)

**Comment by grrosminet** [comment]
Bonjour,
Le tableau comparatif des abonnements est a lire en se disant "Et si je changeait d'abonnement pour un HP/HC, combien ça me couterait ?". C'est pour cela que le tarif est différent.
Par contre ce qui est étrange c'est que tu as "0.2%" de HC en 2023 ==> est-ce que ton PDL est bien configuré dans l'appli ?

**Comment by grrosminet** [comment]
Oui , efface juste les données perso (numéro pdl et token d'identification à minima )

**Comment by Dites33** [comment]
Merci @grrosminet , je l'ai mis dans mon commentaire, si tu vois un truc bizarre ...

Je suis en conso / production (panneaux solaires)

**Comment by grrosminet** [comment]
Effectivement, je ne vois rien d'étrange dans ta config. Peut-etre qu'un rafraichissement complet des données auprès d'enedis pourrait aider (la premiere fois que j'ai installé myelectricaldata, il me manquait une année entière).
Si tu t'intéresse aux couts, attention a maintenir le pric base/HP/HC à jour (tempo est géré différemment)

**Comment by Dites33** [comment]
Merci @grrosminet 

Qu'entends tu par "rafraichissement complet des données auprès d'enedis" ?

**Comment by grrosminet** [comment]
Dans l'interface de ton PDL, en bas a droite de l'écran tu as un menu : vide le cache passerelle , le cache local puis reimporte depuis enedis

**Comment by m4dm4rtig4n** [comment]
Quand tu dit que tu est sur la dernière version, tu parle de la dernière beta cad [v0.9.4.b3](https://github.com/MyElectricalData/myelectricaldata_import/releases/tag/v0.9.4.b3)
Ou la 0.9.3 ?

**Comment by Dites33** [comment]
Hello @m4dm4rtig4n  et @grrosminet 

Version | v0.9.3

J'ai fait un reset cache et reimport, toujours le meme probleme
J'ai fais un export enedis des données et j'ai sur l'année 2023

1 894,05 | kWh HC (22h 6h00)
3 744,62 | kWh HP

Sur myelectricaldata j'ai toujours 100 % sur 2023 en HP, et pourtant mon total conso est le bon, suis perdu :(

**Comment by grrosminet** [comment]
Du coup j'ai mal compris ta demande initiale : je croyais que ton abonnement n'avait pas d'hp/hc : tarif de base .
D'après ton dernier message j'ai compris à l'envers .

Donc l'erreur c'est que tu as configuré ton PDL en BASE (plan : BASE). Tu dois le mettre en HP/HC et refaire un import

**Comment by Dites33** [comment]
Non non tu as bien compris

Mon abonnement est en base. Je voulais juste avoir un comparatif.

 sur le site enedis j’ai activité le relevé horaire il y a deux ans . Du
coup j’ai exporté enedis vers Excel pour 2023 et j’ai pu ressortir les
conso entre 22h et 6h et celles après …

J’ai 33% en hc d’après Excel et 0% dans le camembert d’après myelectrical :(

C’est myelectrical qui me met tout en hp …


Le mer. 17 janv. 2024 à 21:57, grrosminet ***@***.***> a
écrit :

**Comment by grrosminet** [comment]
Puisque tu as configuré myelectricaldata en base il ne te donnera pas de répartition hp/hc. Par contre dans le tableau comparatif il fera le calcul pour toi des 3 possibilité d'abonnement

**Comment by Dites33** [comment]
Et c’est là je crois mon problème.

Je refais des captures demain soir :)


Le mer. 17 janv. 2024 à 22:38, grrosminet ***@***.***> a
écrit :

**Comment by m4dm4rtig4n** [comment]
Normalement même si tu met BASE il devrait calculé le ratio.
Tt à était rework de ce coté sur la 0.10.0 qui ne va pas tarder à sortir, on verra sur cette version si tu as encore le soucis.

**Comment by Dites33** [comment]
Désolé pour le temps de réponse, je ne suis pas en 0.10.0 car Home Assistant ne me le propose pas via l'addon
