### ISSUE TITLE
[FEATURES] - HC et HP en Kwh dans le tableau Conso Journalière + Export CSV ou XLS

### ISSUE THREAD

**Issue by r0m1CH** [MyElectricalData/myelectricaldata_import#462]
Hello,

Si jamais, ca serait cool d'avoir 2 colonnes en plus dans le tableau des conso journalière, ce sont les heures creuses et les heures pleins, limite pour les tempos une pastille de couleur pour savoir quel jour c'était.

Sinon un export de données en fonction de dates (CSV ou XLS) serait parfait car le système enedis... comment dire... enfin tu sais :-)

dispo pour aider/valider si jamais

**Comment by crocro81** [comment]
oui se serait cool. je regardais justement pour ça

**Comment by r0m1CH** [comment]
Juste parfait !

**Comment by m4dm4rtig4n** [comment]
C'est en ligne à partir de la 0.10.0-rc.21.

**Comment by r0m1CH** [comment]
Top merci je vais tester.
