### ISSUE TITLE
[BUG] - Version RC poussée en latest sur Docker Hub

### ISSUE THREAD

**Issue by Passific** [MyElectricalData/myelectricaldata_import#467]
**Description du bug**
Il semble que la version [0.10.0-rc.14](https://hub.docker.com/layers/m4dm4rtig4n/myelectricaldata/0.10.0-rc.14/images/sha256-e0699b4b5ed01736125a5cf9be50073880bf448d65c1340a8c85f58164a6f8cd?context=explore) a été poussé avec les tags [latest-dev](https://hub.docker.com/layers/m4dm4rtig4n/myelectricaldata/latest-dev/images/sha256-e0699b4b5ed01736125a5cf9be50073880bf448d65c1340a8c85f58164a6f8cd?context=explore) et [latest](https://hub.docker.com/layers/m4dm4rtig4n/myelectricaldata/latest/images/sha256-e0699b4b5ed01736125a5cf9be50073880bf448d65c1340a8c85f58164a6f8cd?context=explore).

Or cette version ne semble pas stable, et crash sur mon système.
Je n'ai pas eu le temps de regarder les logs ce matin. Je regarderais ce soir si besoin.

Je pense que c'est une erreur, car je ne dois pas être le seul à suivre la branche latest, qui est (à priori) la version stable.

Merci pour votre super boulot !

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
```
</details>

**Type d'installation**

- [X] Docker
- [ ] HassIO

**Version : latest**

**Comment by m4dm4rtig4n** [comment]
Effectivement j'ai eu un petit rater :)

**Comment by m4dm4rtig4n** [comment]
Je viens de relancer le build de la 0.9.3 qui va rsync la latest.

**Comment by m4dm4rtig4n** [comment]
La latest à était rebuild en 0.9.3 normalement.

**Comment by Passific** [comment]
Merci, je testerais ce soir :)

**Comment by Passific** [comment]
C'est bon, tout marche, merci beaucoup !
