### ISSUE TITLE
Données disparues suite changement de contrat chez EDF

### ISSUE THREAD

**Issue by Jeepmg** [MyElectricalData/myelectricaldata_import#477]
Bonjour,

J'ai changé de contrat tout en restant chez EDF et depuis mes données Enedis sont remises à zero mais pas celles de EDF.

J'ai des sauvegardes de la base SQL mais je ne peux les insérer dans MED sans quelles soient écrasées par Enedis.

Existe t il un moyen de préserver l'existant ?

Merci

**Type d'installation**
 HassIO 

**Version : 9.3

**Comment by m4dm4rtig4n** [comment]
Essaie de définir les 2 dates : 
https://github.com/MyElectricalData/myelectricaldata_import/blob/2dfb99216a7120a14af9b10cdfbcdb25cdef3938/config.exemple.yaml#L74
https://github.com/MyElectricalData/myelectricaldata_import/blob/2dfb99216a7120a14af9b10cdfbcdb25cdef3938/config.exemple.yaml#L75

**Comment by Jeepmg** [comment]
y a de l'idée, mais ca fait le contraire de ce que je souhaiterais :+1: 

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/103240876/ffa02ddd-1082-4dec-a0ad-2e9ca3848c72)

**Comment by Jeepmg** [comment]
si je mets 2024-01-28 comme date, ca me garde bien l'historique, mais ca ne tient pas compte des valeurs postérieures à cette date.  On va y arriver !!!!

Merci

**Comment by Jeepmg** [comment]
J'ai mis la date du nouveau contrat, ca garde l'antériorité. A voir sur la suite.

Merci

**Comment by m4dm4rtig4n** [comment]
> Pourquoi les données acquises ne restent pas définitivement acquises ?

C'est à dire ?
