### ISSUE TITLE
[HELP] - Compatibilité EMQX ?

### ISSUE THREAD

**Issue by therealcorwin** [MyElectricalData/myelectricaldata_import#485]
Bonjour,

J'essaye de configurer MyElectricalData avec EMQX (pas mosquitto Brocker), mais sans succès. 

`
[20:02:17] INFO: mqtt_autodiscover is defined in options, attempting autodiscovery 
[20:02:17] FATAL: No internal MQTT service found. Please install Mosquitto broker
Error : /etc/cont-init.d/91-mqtt_autodiscover.sh exiting 1
`  

Normalement, ma configuration est bonne car elle fonctionne correctement avec Zigbee2Mqtt. 

Ma question est : MED est il compatible avec EMQX ? Ou doit on avoir obligatoirement Mosquitto Broker ?

Ce dernier étant explicitement indiqué dans les logs, je me pose la question. SI EMQX est compatible j'ouvrirais une issue. 

Pour info, le thread sur [HACF](https://forum.hacf.fr/t/myelectricaldata-pb-configuration-avec-emqx/36024)

**Type d'installation**
Hassio

**Version : 0.9.3**

**Comment by therealcorwin** [comment]
Hello,
Je peux clore l'issue. J'ai trouvé la ou ca coince. 

Dans Hassio => Intégration => Mosquitto, l'url est localhost. Cela marchait bien comme cela. Mais pour que cela fonctionne avec MyElectricalData, j'ai modifié l'url avec le nom DNS de la machine. Et depuis l'addon MED se connecte bien à Mqtt. Reste plus qu'a attendre qu'Enedis répare leur site pour valider complètement l'installation.

**Comment by therealcorwin** [comment]
Bonjour, 

Je re ouvre cette issue car je me suis aperçue que l'erreur est toujours malheureusement présente avec. (idem avec la 0.10.0).

J'ai aussi des soucis de donnée absente mais il faut que je regarde plus en profondeur.

**Comment by m4dm4rtig4n** [comment]
Hello @therealcorwin,

Du coup tu as tjr le soucis avec EMQX où c'est un autre soucis de données absente ?

**Comment by therealcorwin** [comment]
Bonjour @m4dm4rtig4n 

Merci pour ta réponse. Alors oui j'ai toujours des soucis. J'ai toujours le message d'erreur `FATAL: No internal MQTT service found.` et je n'ai que très peu d'information sur la card . Au final je sais pas si le message d'erreur a un impact ou pas. Et si oui, lequel :/ 

![card med](https://github.com/MyElectricalData/myelectricaldata_import/assets/5471363/d44c27cf-c87c-4d8c-8c01-f8b232f44c09)

C'est mon premier vrai souci avec HA et mqtt donc je nage un peu dans mes recherches. 

Je trouve 3 sensors  : 

- sensor.linky_XXXXXX_consumption
- sensor.linky_XXXXXX_consumption.last5day
- sensor.linky_XXXXXX_consumption.history

Mais aucun de ce type (pour ecowhat)

- ewEntity: sensor.myelectricaldata_123456_J0    
- ewEntityJ1: sensor.myelectricaldata_123456_J1   
- ewEntityJ2: sensor.myelectricaldata_123456_J2 

J'ai configuré la card de cette manière 

![config card](https://github.com/MyElectricalData/myelectricaldata_import/assets/5471363/d2a57641-e54b-4824-829a-482ef9330f45)

J'ai essayé plusieurs autres sensors sans succès. Je galère un peu à trouver le schmilblik la :(

**Comment by m4dm4rtig4n** [comment]
Est-ce que dans les entities MQTT sur HA tu as bien les 4 appareils suivants :
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/7872518/aa39a4ef-ce6b-4439-88bd-ef587d2532eb)

**Comment by therealcorwin** [comment]
Pour ma Part, j'ai bien le Linky XXXXXXXX et le RTE Ecowatt. Mais pas les autres. Sans doute car je suis en tarif HP/HC. 

Par hasard, j'ai vu sur le dashboard EMQX des pics a plus de 1000+ msg qui étaient recus mais quasi tous dropés, je ne sais pas si ça a lien avec MED. il faut que j'arrive a trouvé cela dans le logs et surtout à le reproduire car y a pas bcp d'historique.

**Comment by m4dm4rtig4n** [comment]
> Pour ma Part, j'ai bien le Linky XXXXXXXX et le RTE Ecowatt. Mais pas les autres. Sans doute car je suis en tarif HP/HC.

Effectivement, ils sont envoyer uniquement si tu active Tempo dans le config.yaml, mais je vais désactiver cette fonctionnalié et envoyer les informations dans 100% de cas dans une prochaine release.

**Comment by m4dm4rtig4n** [comment]
> Par hasard, j'ai vu sur le dashboard EMQX des pics a plus de 1000+ msg qui étaient reçus mais quasi tous dropés, je ne sais pas si ça a lien avec MED. il faut que j'arrive a trouvé cela dans le logs et surtout à le reproduire car y a pas bcp d'historique.

Possible car je renvoie tt les info dans MQTT à chaque import, mais si les valeurs ne change pas peut etre qu'EMQX drop automatiquement.



> Les sensors EcoWatt ce sont bien ceux ci dessous ?

Yep



> La premiere capture est le linky_XXXXXX_consumption, le second linky_XXXXXX_consumption.last5day (Même valeur):

La majorité des changements sans dans les attribues du sensor en lui même.
