### ISSUE TITLE
[BUG] - TNR HS

### ISSUE THREAD

**Issue by m4dm4rtig4n** [MyElectricalData/myelectricaldata_import#507]
@koukihai bon j'ai pété les TNR :D

**Comment by koukihai** [comment]
👋 J'ai essaye de les reparer dans la PR #510, j'en ai profite pour rendre les verifications de logs plus flexibles et pour augmenter le coverage des tests. En esperant que ca soit utile 😄  
N'hesite pas a me pinger si y'a des retouches a faire ! 🙇
