### ISSUE TITLE
[HELP] - No consent can be found for this customer and this usage point.

### ISSUE THREAD

**Issue by jpcasta** [MyElectricalData/myelectricaldata_import#516]
**Description de la fonctionnalité**
Même après avoir re-généré le consentement, depuis 3 jours j’obtiens toujours une erreur de consentement lorsque je soumets une requête pour obtenir les informations de contrat ou d’adresse.
Mais je n’ai pas d’erreur pour obtenir les informations de consommation quotidienne, puissance max quotidienne et puissance moyenne quotidienne toutes les 30 minutes.

Erreur retournée pour les 2 requêtes ci-dessous qui sont celles de la page MyElectricalData :
« No consent can be found for this customer and this usage point. »

Requête pour les données de contrat:
curl -s -X GET « [https://www.myelectricaldata.fr/contracts/xxxxxxxxxxxxxx/ ](https://www.myelectricaldata.fr/contracts/xxxxxxxxxxxxxx/)» -H « Authorization: xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxy »

Requête pour les données d’adresse:
curl -s -X GET « https://www.myelectricaldata.fr/addresses/xxxxxxxxxxxxxx/ » -H « Authorization: xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxy »

**Type d'installation**
Utilisation des requêtes avec NodeRed

**Version : X.X.X**

**Comment by renchap** [comment]
Même souci ici, avec un consentement tout juste donné.

**Comment by m4dm4rtig4n** [comment]
Le soucis est chez Enedis, j'ai ouvert un ticket chez eux semaine dernière.

**Comment by m4dm4rtig4n** [comment]
J'ai eu Enedis ce matin, ils sont sur le sujet.

**Comment by lo92fr** [comment]
Bonjour,

Ils ont pas l'air d'être très pressé de corriger :(.

Laurent.

**Comment by m4dm4rtig4n** [comment]
Tout ce fait par email, il n'y a pas de site qui permet de suivre l'avancement du ticket :/
La seul référence que j'ai c'est : eRITM2967656

**Comment by m4dm4rtig4n** [comment]
Non pas de news d'Enedis pourtant je les ai relancer 2 fois...

**Comment by m4dm4rtig4n** [comment]
Bon je viens d'avoir une discution avec Enedis.
Le soucis intervient uniquement chez les applications qui ont était migrer de la V4 à la V5 chez eux et ils sont tjr en cours d'analyse...

Une solution pourrait potentiellement corriger le soucis, mais ca m'oblige à récrée une nouvelle application chez eux.
L'inconvéniant de cette solution => La totalité des utilisateurs devront refaire un consentement...

**Comment by jpcasta** [comment]
Refaire le consentement ne m’ennuie pas vraiment…. Ce qui m’ennuie c’est qu’ils ne trouvent pas le problème alors que vous avez fait l’effort de migrer de la V4 à la V5!.
Je pense qu’ils n’y mettent pas de la bonne volonté car ça fait bientôt 4 mois que l’erreur existe.
Merci de nous tenir au courant.

**Comment by Gixy31** [comment]
Je vais prendre le temps de câbler la liaison série de mon Linky. J'aurai les mêmes infos et ne dépendrai plus de ces incapables. C'est quand même incroyable et bien à l'image de tout le reste.

**Comment by Gixy31** [comment]
C'est fait, Linky connecté à un ESP32 via interface TeleInfo de Charles Hallard. Tout est disponible en temps réel. MQTT, Nodered, InfluxDB et Grafana et hop, un tableau de bord parfait, j'ai même affiché la consommation en Euros selon le tarif actif (suis en Tempo).  Bref, plus la peine de s'embêter avec ENEDIS et leur API toujours en panne.
J'ai paramétré influxDB pour garder les données à la minute pendant 4 semaine, puis moyennées à l'heure pendant 1 an et enfin au jour pendant 10 ans avant effacement. Gain de volume de stockage à la clé.

**Comment by m4dm4rtig4n** [comment]
> C'est fait, Linky connecté à un ESP32 via interface TeleInfo de Charles Hallard. Tout est disponible en temps réel. MQTT, Nodered, InfluxDB et Grafana et hop, un tableau de bord parfait, j'ai même affiché la consommation en Euros selon le tarif actif (suis en Tempo). Bref, plus la peine de s'embêter avec ENEDIS et leur API toujours en panne. J'ai paramétré influxDB pour garder les données à la minute pendant 4 semaine, puis moyennées à l'heure pendant 1 an et enfin au jour pendant 10 ans avant effacement. Gain de volume de stockage à la clé.

Perso j'ai les 2, je me sert du TIC pour le temps réel principalement et les API pour l'historique.

**Comment by Gixy31** [comment]
C'est pour cela que je garde les données avec InfluxDB. Mais on peut aussi consulter l'historique sur le site du fournisseur, ou avec des sites comme HelloWatt qui utilisent aussi les API avec consentement. Avec HelloWatt j'ai en simultané ma conso et ma production photovoltaïque, et qui me montre que quand il fait beau je gagne de l'argent ( j'ai un contrat qui date de 2011 avec rachat à 0,61€/kWh ) !

**Comment by m4dm4rtig4n** [comment]
Tt est de nouveau opérationnel dont les 2 endpoints addresses & contract.

=> Je clos l'issue :)

**Comment by Gixy31** [comment]
Impossible de refaire le consentement...

**Comment by jpcasta** [comment]
Tout refonctionne correctement!
Merci pour tout!!

**Comment by Gixy31** [comment]
Je confirme, après qques ajustements cela fonctionne de nouveau

**Comment by Gixy31** [comment]
Et hop, voilà deux jours que cela ne fonctionne encore plus. Ces programmeurs devraient se faire embaucher chez Boeing, ils ont le bon profil...

**Comment by lo92fr** [comment]
Bonjour,

Ils avaient signalé une fenêtre de maintenance le 12 août entre 17h et 20h.
Peut être que tu est tombé sur ce créneau ?

cdt,
    Laurent.

**Comment by Gixy31** [comment]
Que nenni, toujours rien depuis le 11 août 0h. "Merci de ressayer plus tard", sauf que "plus tard" commence à durer... En même temps, je n'en ai plus besoin depuis que j'ai connecté la prise TIC de mon Linky, et là c'est fiable.

**Comment by lo92fr** [comment]
Autant pour moi, je viens de tester, et effectivement encore casser sur les endpoints des contrats :(

**Comment by lo92fr** [comment]
grrrrr

**Comment by lo92fr** [comment]
D'un autre côté, une équipe de dev qui fait un update le même jour des environnements d'homologation et de production.
C'étais prévisible ...

**Comment by lo92fr** [comment]
Pour info, 

![image](https://github.com/user-attachments/assets/dfc6a106-0a9c-4e98-a2d8-bcfdaf95a486)

**Comment by Gixy31** [comment]
Youpee tralala, ça remarche, pour combien de temps...

**Comment by Gixy31** [comment]
Trop beau pour être vrai, ça fonctionnait bien depuis quelques mois et d'un coup depuis trois jours c'est mort. Encore une fausse manip' de nos champions du monde du logiciel public.

**Comment by Gixy31** [comment]
Sans rien toucher, ça remarche, jusqu'à la prochaine fois...
