### ISSUE TITLE
[BUG] - appel GET toutes les 5 secondes sur port différent

### ISSUE THREAD

**Issue by jphii** [MyElectricalData/myelectricaldata_import#519]
Toutes les 5 secondes j'ai un enregistrement de ce type dans le journal de l'addon. 
My electricaldata
2024-04-01 10:51:56.053 -     INFO : 127.0.0.1:52934 - "GET / HTTP/1.1" 200
le port change à chaque fois

En parallèle j'ai une entrée dans le journal host

host
2024-04-01 08:52:01.092 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-9318ee4de2c2b99125f2534816ef3665d7ef49375d4e167624d80ee72d6196e6-runc.eWwnnL.mount: Deactivated successfully.

ce comportement me parait étrange

<details>
<summary>cycle: 14400
debug: false
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws: # FOR ENERGY TAB
  enable: true
  ssl: false
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  url: 192.168.1.151:8123
  url: 192.168.1.151:8123
  max_date: "2021-06-01"
  purge: false
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: linky/autogen
  enable: true
  hostname: 192.168.1.151
  method: asynchronous
  org: '-'
  port: 8086
  scheme: http
  token: homeassistant:Yi?c8nQTs8Mz
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: 192.168.1.151
  password: xxxxxxxxxxxxxxxxxxxxxx
  port: 1883
  prefix: linkyjp
  qos: 0
  retain: true
  username: toto
myelectricaldata:
  '25176121484242':
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.2516'
    consumption_price_hc: '0.2068'
    consumption_price_hp: '0.27'
    enable: 'true'
    name: 169 Paradis
    offpeak_hours_0: 23h00-7h00
    offpeak_hours_1: 23h00-7h00
    offpeak_hours_2: 23h00-7h00
    offpeak_hours_3: 23h00-7h00
    offpeak_hours_4: 23h00-7h00
    offpeak_hours_5: 23h00-7h00
    offpeak_hours_6: 23h00-7h00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
tempo:
  enable: true
  price_blue_hc: 0.1296
  price_blue_hp: 0.1609
  price_red_hc: 0.1568
  price_red_hp: 0.7562
  price_white_hc: 0.1486
  price_white_hp: 0.1894
wipe_influxdb: false</summary>

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
```
</details>

**Type d'installation**

- [ ] Docker
- [x ] HassIO

**Version : 0.12.0**

**Comment by m4dm4rtig4n** [comment]
C'est le health check du conteneur qui check que le service est UP.
Rien de grave.
