### ISSUE TITLE
[BUG] - Problème de consentement

### ISSUE THREAD

**Issue by alois-gaucher** [MyElectricalData/myelectricaldata_import#521]
**Description du bug**
Lors de l'inscription sur https://myelectricaldata.fr/ "Faire la demande de consentement", je suis redirigé sur la page Enedis et mon compteur est grisé avec la mention "compteur non compatible"

Si j'ouvre la console de mon navigateur, j'ai ces informations:

```
Is Connected: Yes
header.js:1 fonction verificationUrlDansWhiteList ==> 
header.js:1 Resultat url dans la whiteList:  false
header.js:1 Vérification disponibilté du Zuul
header.js:1 url n'est pas dans la whitlist !
header.js:1 Is Connected: Yes
header.js:1 fonction appelValidationCGU ==> 
header.js:1 dateCGU : 2021-08-12
header.js:1 dateCGUUser : 2021-08-12
header.js:1 Validation des CGU non nécessaires
```

Sauriez-vous m'aiguiller sur la marche à suivre ? S'agit t-il d'un problème côté Enedis ?

Merci !
<details>
<summary>Configuration (config.yaml)</summary>

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
```
</details>

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : X.X.X**

**Comment by Keltharak** [comment]
J'ai exactement le même problème de mon coté. J'ai pensé à une limitation Enedis du nombre de partage que l'on peut faire (j'en avais déjà 2 : HelloWatt et mon fournisseur d'élec) mais j'en ai supprimé 1 pour voir et ça ne change rien pour le consentement MyElectricalData :(

**Comment by m4dm4rtig4n** [comment]
Vous êtes plusieurs à avoir le soucis a priori....
Je vais essayer de contacter Enedis pour leur remonter le souci...

**Comment by TF-chrobiche** [comment]
Meme probleme sur deux compteurs.

**Comment by m4dm4rtig4n** [comment]
Vous avez encore le soucis ?
Chez moi ca semble fonctionner :
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/7872518/480f3e82-70a6-4d96-8ff1-f25981de56da)

**Comment by Keltharak** [comment]
Yes ça fonctionne chez moi aussi !

Merci pour l'info
________________________________
De : Clément VALENTIN ***@***.***>
Envoyé : mardi 23 avril 2024 09:37
À : MyElectricalData/myelectricaldata_import ***@***.***>
Cc : Keltharak ***@***.***>; Manual ***@***.***>
Objet : Re: [MyElectricalData/myelectricaldata_import] [BUG] - Problème de consentement (Issue #521)


Vous avez encore le soucis ?
Chez moi ca semble fonctionner :
image.png (view on web)<https://github.com/MyElectricalData/myelectricaldata_import/assets/7872518/480f3e82-70a6-4d96-8ff1-f25981de56da>

**Comment by m4dm4rtig4n** [comment]
@alois-gaucher chez toi aussi ?
