### ISSUE TITLE
FATAL: The app has crashed. Are you sure you entered the correct config options?

### ISSUE THREAD

**Issue by Dim3333** [MyElectricalData/myelectricaldata_import#527]
Bonjour,

Alors que tout fonctionnait depuis plusieurs mois, j'ai subitement des arrêts de l'add-on avec ce message dans le journal ;

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/43283756/a62b462a-af3b-43ad-9a3e-b17264710125)

Ma version :
Core
2024.4.4
Supervisor
2024.04.0
Operating System
12.2
Interface utilisateur
20240404.2

Myelectricaldata
v0.12.0

Edit; Apres redémarrage, idem:

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/43283756/cc6ca88d-b968-4895-bb6b-15ce2ea8c1dc)

**Comment by m4dm4rtig4n** [comment]
Hello,
Vu l'erreur il semblerais qu'un service tier "kill" le service car il consomme trop de mémoire (oomkilled).
Est-ce que tu n'aurais pas limiter l'utilisation mémoire du conteneur ?

**Comment by Dim3333** [comment]
Hi,
Je n'ai rien touché. J'ai alloué 2Go à la VM (je suis Proxmox).

**Comment by m4dm4rtig4n** [comment]
Et qu'est ce qui tourne sur la VM a par myelectricaldata ?

**Comment by Dim3333** [comment]
En fait, HAOS tourne en VM.

**Comment by m4dm4rtig4n** [comment]
2go pour haos tu est ultra light pas étonnant qu'il kill le conteneur :/
Ta des traitements de fond qui prennent un peu de ressources 🫤

**Comment by Dim3333** [comment]
Pas sur de comprendre la question ? Comme quoi pour les traitements de fond ?

Sinon supprimer Proxmox et installer HAOS. De cette façon, une couche logicielle en moins et 4Go alloué pour HAOS.

**Comment by m4dm4rtig4n** [comment]
Lors de l'importation des data, je fait un petit traitement pour le comparateur d'abonnement qui reprend la totalité des data pour calculé le tableau suivant :
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/7872518/87333809-0f01-4cb7-a033-0e0218144129)

Et donc tt les données montent en mémoire pour le calcul et génère probablement un dépassement de mémoire.
Et quand tu n'a plus de RAM disponible, le système vient kill automatiquement les services les plus consommateur de mémoire.

**Comment by Dim3333** [comment]
Ok. Je comprends mieux. J'ai relancé MED hier soir et pour l'instant ça tourne.
Ne pouvant pas upgrader la RAM, je vais supprimer la couche Proxmox.

**Comment by m4dm4rtig4n** [comment]
Si tu utilise une machine avec uniquement 4Go de RAM, je te déconseille effectivement de passer par Proxmox qui va te pomper un peu de ressource pour rien en fin de compte.

**Comment by Dim3333** [comment]
Oui, effectivement. Même si depuis plus d'un an, ça tourne nickel.
Mais je pense qu'avec les MAJ  mensuelles HA, les différentes intégrations qui se multiplient, mon système s'est alourdi.
Dès que j'ai le temps, je supprime Proxmox pour ne garder que HAOS.
