### ISSUE TITLE
[FEATURES] - Laisser une option dasn config.yaml pour définir Puissance Maximale si l'info n'est pas renseignée automatiquement

### ISSUE THREAD

**Issue by r-jean-pierre** [MyElectricalData/myelectricaldata_import#528]
Bonjour,

Je dois être un des malchanceux qui tombe dans le cas "_Les données ont été récupérées via les API d'Enedis et ne sont pas toujours correctement mises à jour par Enedis. Vérifiez bien vos horaires HC/HP et votre date d'activation. Vous pouvez surcharger ces valeurs dans la configuration du point de livraison._"

Donc concrètement, rien n'est rempli dans la partie "**Contrat**" de l'onglet "MyElectricalData"

Ce n'est pas très dérangeant vu la contrepartie d'avoir pu récupérer plusieurs années de conso et d'avoir déjà mes stats toutes faites!

Le seul glitch est que comme (j'imagine) "**Puissance souscrite**" n'est pas renseignée, j'imagine (encore une fois) que dans la partie "**Puissance Maximale**", je ne bénéficie pas de la coloration orange/rouge si on dépasse 90 ou 100% de son max kVA

Du coup je confirme aussi que mon sensor mqtt linky, n'a lui aussi pas d'infos pour "**Subscribed power**" et par exemple "ActivationDate"

Voilà je sais pas si qq'un l'avait vu et/ou si c'est simple/utile à mettre en oeuvre, mais vu que l'intégration touche la perfection, il ne reste plus qu'à corriger indirectement les boulettes d'enedis :-D

**Comment by m4dm4rtig4n** [comment]
Hello @r-jean-pierre,

Les endpoints qui permettent de récupérer les informations du type contrat & adresse sont malheureusement HS depuis plus d'un mois chez Enedis (cf. https://github.com/MyElectricalData/myelectricaldata_import/issues/516) et c'est probablement pour cela que tu ne récupère pas correctement les information sur tes HC/HP ainsi que ta puissance souscrite.

**Comment by r-jean-pierre** [comment]
> Hello @r-jean-pierre,
> 
> Les endpoints qui permettent de récupérer les informations du type contrat & adresse sont malheureusement HS depuis plus d'un mois chez Enedis (cf. #516) et c'est probablement pour cela que tu ne récupère pas correctement les information sur tes HC/HP ainsi que ta puissance souscrite.

Ha okay, je pensais que c'était parceque j'étais chez totalenergies ou un autre cas particulier.
Donc suffirait d'attendre qu'un jour enedis daigne bien vouloir faire remonter les infos?

**Comment by m4dm4rtig4n** [comment]
Yep
