### ISSUE TITLE
[HELP] - Internal Server Error.

### ISSUE THREAD

**Issue by lepalois** [MyElectricalData/myelectricaldata_import#530]
Bonjour,
J’ai un léger souci, après installation de InfluxDB (version5) et MyElectricalData (version 0.12.0) j’ai un joli Internal Server Error.
Il n’y a aucune entité de créer également.
Parfois, j'ai la page qui s'affiche mais il n'y a pas grand chose qui remonte voir les images ci-dessous. Souvent quand la page s'affiche j'ai de nouveau Internal Server error.

![HA_MyElectricaldata_4](https://github.com/MyElectricalData/myelectricaldata_import/assets/83166773/09afa97d-42ec-43cc-81da-39715b8d3c78)
![HA_MyElectricaldata_3](https://github.com/MyElectricalData/myelectricaldata_import/assets/83166773/327a236c-340e-4c59-a711-9c9166ab29ce)
![HA_MyElectricaldata_2](https://github.com/MyElectricalData/myelectricaldata_import/assets/83166773/3431982d-f55b-4824-83fc-ccdf071afb78)

**Type d'installation**
HassIO  (VM Synology)

**Version : 0.12.0**

**Comment by m4dm4rtig4n** [comment]
Hello,

Il me faudrait des logs pour t'aider sur le sujet :)

**Comment by lepalois** [comment]
Bonjour, merci du rapide retour.
J'ai mis les logs en PJ si cela te convient.
En reprenant le fichier myelectricaldata/config.yaml présent ici, je n'ai plus l'erreur "Internal Server Error" par contre je n'ai aucun sensor.
J'ai uniquement en entité :
- update.myelectricaldata_update

En MQTT
- EDF Tempo
- RTE Tempo
- linky POL
- RTE EcoWatt
Et je n'ai toujours rien sur mon contrat qui apparait.

En te remerciant.

[Starting....txt](https://github.com/MyElectricalData/myelectricaldata_import/files/15417954/Starting.txt)

**Comment by m4dm4rtig4n** [comment]
Les logs sont pas complet, essaie d'ouvrir dans ton navigateur MED et de changer l'url en mettant : 
`https://URLVERSTONMED/import/TONPDL/home_assistant` 

Et post moi ton fichier de log après ouverture de la page web.
