### ISSUE TITLE
[BUG] - Impossible d'installer la version 0.13.1 "Manifest unknown"

### ISSUE THREAD

**Issue by Atarinside** [MyElectricalData/myelectricaldata_import#540]
**Description du bug**
Merci de me détailler au mieux le bug et une procédure pour le reproduire si possible.

Bonjour,
j'ai un message d'erreur en voulant installer la mise à jour depuis home assistant

Message d'erreur :
Échec de l'appel du service update/install. Error updating MyElectricalData: Can't install ghcr.io/alexbelgium/myelectricaldata-armv7:0.13.1: 500 Server Error for http+docker://localhost/v1.44/images/create?tag=0.13.1&fromImage=ghcr.io%2Falexbelgium%2Fmyelectricaldata-armv7&platform=linux%2Farm%2Fv7: Internal Server Error ("manifest unknown")

**Type d'installation**

- [ ] Docker
- [ x] HassIO

**Version : **
Core 2024.5.5
Supervisor 2024.05.1
Operating System 12.3
Interface utilisateur 20240501.1

**Comment by m4dm4rtig4n** [comment]
J'ai remonter le soucis sur le repo hassio :
https://github.com/alexbelgium/hassio-addons/pull/1414

**Comment by Sylv1F** [comment]
Problème résolu pour moi depuis, relancer l'update.

**Comment by m4dm4rtig4n** [comment]
Fix par Alex :)

**Comment by Atarinside** [comment]
Merci pour votre reactivité ! Je confirme que ca fonctionne maintenant.

**Comment by machintrucbidule** [comment]
J'ai pas eu de soucis pour installer la 0.13.1, par contre même erreur sur la 0.13.2 :
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/75478334/7e8bfd09-dc3b-4498-bc68-569a965e45c5)

**Comment by Sylv1F** [comment]
C'est ok pour l'update 0.13.2 sur HA

**Comment by machintrucbidule** [comment]
C'est passé aussi, merci 😊
