### ISSUE TITLE
Pas de graphique à jour depuis 0.13.2

### ISSUE THREAD

**Issue by Jeepmg** [MyElectricalData/myelectricaldata_import#544]
**Description du bug**
Pas de mise à jour du graphique des valeurs de consommation mensuelles

![graph](https://github.com/MyElectricalData/myelectricaldata_import/assets/103240876/4c885ad8-7104-4a14-be30-150475d58a64)

La valeur de mai est juste.

<details>

<summary>Configuration (config.yaml)</summary>

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
```
</details>

**Type d'installation**

- [ ] HassIO

**Comment by m4dm4rtig4n** [comment]
@Jeepmg rien de spécial dans les logs ?

**Comment by Jeepmg** [comment]
@m4dm4rtig4n perso je ne vois rien de spécial.

**Comment by Jeepmg** [comment]
@m4dm4rtig4n Je peux revenir à la version 0.13 dans HA ?

**Comment by Jeepmg** [comment]
Je n'en ai fait que 2 ou 3 et j'ai eu le message directement à la 1ere demande. Je peux revenir à la version 0.13 ? Cordialement Michel GRASSA +33 650334760 Le 4 juin 2024 à 16:28, Clément ***@***.***> a écrit : Normalement oui sans soucis. SI tu attaque les endoints sans le /cache c'est 50 query max / jours. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you were mentioned. Message ID: ***@***.***>
