### ISSUE TITLE
[HELP] - Mon contrat - Pas de données

### ISSUE THREAD

**Issue by Dan512512** [MyElectricalData/myelectricaldata_import#550]
Bonjour,

J'ai supprimé cache.db, et je n'ai plus les données de mon contrat qui s'affiche - même après avoir renouvelé mon token chez Enedis
![MyElectricalData](https://github.com/MyElectricalData/myelectricaldata_import/assets/156787939/6c5e58c5-fe7c-490c-9efa-cab7ddc3fc37)

**Type d'installation**
RaspberryPi4

**Version : 2024.6.2**

**Comment by m4dm4rtig4n** [comment]
Duplicate : https://github.com/MyElectricalData/myelectricaldata_import/issues/516
