### ISSUE TITLE
[HELP] - Données plus présentes depuis 17 juillet

### ISSUE THREAD

**Issue by TheFtg** [MyElectricalData/myelectricaldata_import#573]
Bonjour,

D'abord merci pour votre travail.

Mon installation a fonctionné parfaitement pendant quelques mois mais depuis Juillet, j'ai plus de donnée.

J'ai vu sur le site qu'il y avait un souci chez Enedis.

Avez-vous une idée de la résolution du souci ?

Merci d'avance de votre réponse

David

**Comment by m4dm4rtig4n** [comment]
Refait un consentement :)

**Comment by TheFtg** [comment]
Merci ! Ca a fonctionné !
